### ISSUE TITLE
Latest caimito config.properties has windows line endings 

### ISSUE THREAD

**Issue by fifieldt** [ngasiproj/caimito#3]
Very minor issue ....

The lastest config.properties appears to have windows line endings (the type that appear in vim as ^M) ;)
# file,openstack^M

^M
resource=file^M
# A Container or Bucket^M

cloud.store=store1^M
cloud.username=SLOS11111-1:SL11111^M
cloud.api.key_password=fffffffffffffffffffffffffffffffffff^M
^M
cloud.url=https://dal05.objectstorage.softlayer.net/auth/v1.0/^M
# cloud.url=https://dal05.objectstorage.service.networklayer.com/auth/v1.0^M

**Comment by ngasiproj** [comment]
Gee - I thought git automatically converts to nix. Anyway update pushed to github.
Regards

-----Original Message-----
From: "Tom Fifield" reply@reply.github.com
Sent: Tuesday, June 5, 2012 8:32pm
To: "ngasiproj" gabrielw@ngasi.com
Subject: [caimito] Latest caimito config.properties has windows line endings (#3)

Very minor issue ....

The lastest config.properties appears to have windows line endings (the type that appear in vim as ^M) ;)

#file,openstack^M
^M
resource=file^M
#A Container or Bucket^M
cloud.store=store1^M
cloud.username=SLOS11111-1:SL11111^M
cloud.api.key_password=fffffffffffffffffffffffffffffffffff^M
^M
cloud.url=https://dal05.objectstorage.softlayer.net/auth/v1.0/^M
#cloud.url=https://dal05.objectstorage.service.networklayer.com/auth/v1.0^M

---

Reply to this email directly or view it on GitHub:
https://github.com/ngasiproj/caimito/issues/3
