### ISSUE TITLE
Caimito support For HP cloud

### ISSUE THREAD

**Issue by gleesonc** [ngasiproj/caimito#4]
I have been trying of late to set up your Caimito WebDav server to my Hp Cloud swift account. I have been getting errors from my implementation. I was wondering is your software compatible with Hp cloud? Could you tell me of Caimito will work with the keystone module from openctack? Or if there is anywhere else which you may think that I may be going wrong? Thanks for your time.

At the moment I am getting a 500 internal server error message. I have tried different variations of user credentials in the  
"/usr/caimito/webapps/WEB-INF/caimito/config.properties" file - (In case I had the wrong input). However nothing seemed to work. Any help would be greatly appreciated.

**Comment by ngasiproj** [comment]
Hi Conor,
What does the Caimito logs show?

-----Original Message-----
From: "gleesonc" reply@reply.github.com
Sent: Wednesday, June 6, 2012 12:17pm
To: "ngasiproj" gabrielw@ngasi.com
Subject: [caimito] Caimito support For HP cloud (#4)

I have been trying of late to set up your Caimito WebDav server to my Hp Cloud swift account. I have been getting errors from my implementation. I was wondering is your software compatible with Hp cloud? Could you tell me of Caimito will work with the keystone module from openctack? Or if there is anywhere else which you may think that I may be going wrong? Thanks for your time.

At the moment I am getting a 500 internal server error message. I have tried different variations of user credentials in the  
"/usr/caimito/webapps/WEB-INF/caimito/config.properties" file - (In case I had the wrong input). However nothing seemed to work. Any help would be greatly appreciated.

---

Reply to this email directly or view it on GitHub:
https://github.com/ngasiproj/caimito/issues/4

**Comment by gleesonc** [comment]
Hello,

I haven't came across any log files thus far. (I only have the log information on caimito startup) so here it is,

"INFO: Server startup in 3827 ms
java.lang.IllegalStateException: Target host must not be null, or set in parameters.
    at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:651)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:353)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)
...
...
...                                                                                                                                     "

**Comment by gleesonc** [comment]
Resolved. tenant ID must be added to username. Illustrated by tenantid:username.

Thanks for the help.

**Comment by ngasiproj** [comment]
Excellent. Glad to hear it works with HP Cloud.
