### ISSUE TITLE
Configuration Query

### ISSUE THREAD

**Issue by gleesonc** [ngasiproj/caimito#5]
Hello folks,

I am using the HP implementation of openstack with my caimito server.

I was wondering is their any possible way to configure multiple containers to a server instance at any one time. Furthermore I was wondering can multiple users be configured to a single erver also.

Any help on this issue would be greatly appreciated.

Thanks,
Conor

**Comment by ngasiproj** [comment]
Hi Conor,
With regards to multiple storage, that is being consider for a future release but not available at the moment.
That would be a configuration setting in config.properties like:
multiple.storage=true
And if limiting to a specific list of containers or buckets is desired:
cloud.storage.list=store1,store2,etc
The containers or buckets would be the first sub directory level from the root.

Multiple users are presently supporte. Please take a look at the "Configuring Users" section here:
http://caimito.ngasi.com/
A better doc is on the todo list.
Regards

**Comment by gleesonc** [comment]
Hello again,

Thank you for the detailed response. I apologise for the wording of my first query. I was meaning to ask is Caimito configurable to multiple openstack accounts, rather than Caimito users. However I have a much better understanding from your response. I will keep an eye on future developments.

**Comment by ngasiproj** [comment]
Hi Conor,
Caimito is not configurable to multiple openstack accounts. Just curious how do you see that  - functionality wise?

Regards

-----Original Message-----

**Comment by gleesonc** [comment]
I figured that if it doesn't support multiple containers that it would not support multiple account either. (Multiple accounts would mean multiple containers). Is that what you were wondering?

**Comment by ngasiproj** [comment]
Hi Conor,
You may have multiple containers associated with 1 openstack account.
That said there are a number of scenarios.
1)CLOUD PROVIDER e.g. HP Cloud
Multiple Openstack Accounts and Multiple Containers - issue here is conflicts with containers with the
same name. Unless a root path alias is assigned to each openstack account e.g.
container1 for myaccount1 maps to myaccount1/container1 etc. Cloud customers must accept whatever user names are available - e.g. if user1 is already taken by another cloud customer, then must choose another name. Unless users are forced to include tenant name with login e.g. - tenant1:user1 OR use the root path to obtain the cloud owner user belongs to. Benefits here - fewer instances of Caimito and can be offered as a service.
2)Cloud customer
1 Openstack Account and Multiple Containers - no conflicts
3)Reseller or Enduser
1 Container

Some thoughts and ramblings that hopefully did not confuse you.

-----Original Message-----

**Comment by gleesonc** [comment]
Thanks for your reply. Yes, I understand the workings of openstack accounts. I was curious to know could one Caimito instillation be configured to multiple accounts at once. For example,

Is it possible to configure two openstack accounts to the one caimito instance, Account1 and account 2.

**Comment by ngasiproj** [comment]
So in this case there would be no public paths?
e.g. account1 has path myhtml which is protected. account2 which also has myhtml path BUT not protected won't be able to coexist UN LESS an extra root path that identifies the openstack account OR perhaps virtual hosting.
All access would require authentication - and from the auth, corresponding openstack account would be determined.

-----Original Message-----

**Comment by ngasiproj** [comment]
Hi Conor,
Please see the following issue:
https://github.com/ngasiproj/caimito/issues/7
